board:
    id: 1196
    name: AWS Ops Board
    type: kanban
epic:
    name: customfield_10008
    link: ""
installation: Cloud
issue:
    fields:
        custom:
            - name: Email Marketer
              key: customfield_17267
              schema:
                datatype: user
            - name: Flex Path
              key: customfield_16879
              schema:
                datatype: array
                items: option
            - name: Approvers
              key: customfield_16906
              schema:
                datatype: array
                items: user
            - name: GL Code 4 %
              key: customfield_16715
              schema:
                datatype: number
            - name: Copyediting Phase
              key: customfield_15500
              schema:
                datatype: option
            - name: Department
              key: customfield_13502
              schema:
                datatype: option
            - name: Final Path
              key: customfield_16902
              schema:
                datatype: option
            - name: Work Item Type
              key: customfield_16882
              schema:
                datatype: option
            - name: Requested By
              key: customfield_12300
              schema:
                datatype: string
            - name: Team
              key: customfield_13800
              schema:
                datatype: any
            - name: GL Code 3 %
              key: customfield_16714
              schema:
                datatype: number
            - name: Start date
              key: customfield_16829
              schema:
                datatype: date
            - name: Preorder Date
              key: customfield_17607
              schema:
                datatype: date
            - name: GL Code %
              key: customfield_16712
              schema:
                datatype: number
            - name: URL
              key: customfield_17098
              schema:
                datatype: string
            - name: Pick your Project
              key: customfield_17598
              schema:
                datatype: project
            - name: WS Environment
              key: customfield_16838
              schema:
                datatype: option
            - name: High Availability Team
              key: customfield_15000
              schema:
                datatype: option
            - name: GL Code 2 %
              key: customfield_16713
              schema:
                datatype: number
            - name: Sprint
              key: customfield_10006
              schema:
                datatype: array
                items: json
            - name: WS Sub-WIT
              key: customfield_16868
              schema:
                datatype: option
            - name: Flagged
              key: customfield_10002
              schema:
                datatype: array
                items: option
            - name: Impact
              key: customfield_17106
              schema:
                datatype: option
            - name: GL Code 4
              key: customfield_16756
              schema:
                datatype: option
            - name: GL Code 3
              key: customfield_16755
              schema:
                datatype: option
            - name: GL Code
              key: customfield_16753
              schema:
                datatype: option
            - name: Start Date.
              key: customfield_10500
              schema:
                datatype: date
            - name: Urgency
              key: customfield_17112
              schema:
                datatype: option
            - name: Delivery method for photos
              key: customfield_17078
              schema:
                datatype: string
            - name: GL Code 2
              key: customfield_16754
              schema:
                datatype: option
            - name: Development
              key: customfield_13300
              schema:
                datatype: any
            - name: Parent Link
              key: customfield_13200
              schema:
                datatype: any
            - name: Epic Link
              key: customfield_10007
              schema:
                datatype: any
            - name: Severity
              key: customfield_11613
              schema:
                datatype: option
            - name: Dev Needs
              key: customfield_16865
              schema:
                datatype: array
                items: option
            - name: Root Cause
              key: customfield_11614
              schema:
                datatype: option
            - name: Organizations
              key: customfield_14100
              schema:
                datatype: array
                items: sd-customerorganization
            - name: Request participants
              key: customfield_16842
              schema:
                datatype: array
                items: user
            - name: Epic Color
              key: customfield_10010
              schema:
                datatype: string
            - name: Associate Producer
              key: customfield_17637
              schema:
                datatype: user
            - name: Epic Priority
              key: customfield_11800
              schema:
                datatype: option
            - name: Epic Name
              key: customfield_10008
              schema:
                datatype: string
            - name: Epic Status
              key: customfield_10009
              schema:
                datatype: option
            - name: Producer
              key: customfield_16881
              schema:
                datatype: user
            - name: Epic/Theme
              key: customfield_10003
              schema:
                datatype: array
                items: string
            - name: Editor
              key: customfield_16887
              schema:
                datatype: user
    types:
        - id: "12981"
          name: Systems Engineering
          handle: Systems Engineering
          subtask: false
        - id: "12980"
          name: Software Engineering
          handle: Software Engineering
          subtask: false
        - id: "10800"
          name: Defect
          handle: Defect
          subtask: true
        - id: "12955"
          name: Sub-task - Dev Only
          handle: Sub-task - Dev Only
          subtask: true
        - id: "10000"
          name: Epic
          handle: Epic
          subtask: false
login: mike.porter@ramseysolutions.com
project:
    key: WS
    type: classic
server: https://ramseysolutions.atlassian.net
